### ISSUE TITLE
how to check a NSArray with predicate

### ISSUE THREAD

**Issue by mrchenhao** [reygonzales/RPJSONValidator#15]
without index of array

**Comment by reygonzales** [comment]
Can you post sample JSON?

**Comment by mrchenhao** [comment]
for example

server return such as:
[
    {
        "name": "zhangsan",
        "age": 18
    },
    {
        "name": "zhangsan",
        "age": 18
    },
{
        "name": "zhangsan",
        "age": 18
    }
more and more person
]


i want to use this to validate 
{
        "name": String,
        "age": number
 }

**Comment by reygonzales** [comment]
I actually haven't thought of this case yet. You can wrap the array with a dictionary as a workaround for now:

NSDictionary *json = @{
     @"elements" : 
};

```
NSError *error;
NSArray *json = @[@{@"name" : @"zhangsan", @"age" : @18}, @{@name : @"rey", @"age" : @18}];

if(![RPJSONValidator validateValuesFrom: json
                       withRequirements:@{
                               @"friends" : [RPValidatorPredicate.isArray valuesWithRequirements:@{
                                       @"name" : RPValidatorPredicate.isString,
                                       @"age"  : RPValidatorPredicate.isNumber}]
                       }
                                  error:&error]) {
    ...
} else {
    ...
}```

**Comment by reygonzales** [comment]
I don't have a built-in solution for this yet, but you can use this workaround for now:

NSArray *elements = @[@{@"name" : @"zhangsan", @"age" : @18}, @{@"name" : @"rey", @"age", @18}];
NSDictionary *json = @{@"elements" : elements};

**Comment by mrchenhao** [comment]
ok  that's the way I do now 
I think is's a good feature,may I pull request for this ?

**Comment by reygonzales** [comment]
Sure thing, I'll review everything before I pull, test, and release
